SET LOCK_MODE 3;              
;             
CREATE USER IF NOT EXISTS SA SALT '39e896fee3e8c8a6' HASH '51a115b53d555bce0780e0baf7950d1ce842dcee79f42f9442a6c6e867de9c67' ADMIN;           
CREATE CACHED TABLE PUBLIC.MST_BARANG(
    PLU VARCHAR(8) NOT NULL,
    BARCODE1 VARCHAR(30),
    BARCODE2 VARCHAR(30),
    HARGA_BELI DECIMAL(19, 2),
    HARGA_MEMBER DECIMAL(19, 2),
    HARGA_NORMAL DECIMAL(19, 2),
    ISI_PEMBELIAN INTEGER NOT NULL,
    JUAL BOOLEAN NOT NULL,
    LIMIT_WARNING BOOLEAN NOT NULL,
    NAMA_BARANG VARCHAR(100),
    SATUAN VARCHAR(20),
    SATUAN_PEMBELIAN VARCHAR(20),
    STOK_GUDANG INTEGER NOT NULL,
    STOK_MAX INTEGER NOT NULL,
    STOK_MIN INTEGER NOT NULL,
    TOTAL_KUANTITAS_PEMBELIAN_GUDANG INTEGER NOT NULL,
    TOTAL_KUANTITAS_PEMBELIAN_TOKO INTEGER NOT NULL,
    TOTAL_KUANTITAS_PENJUALAN_GUDANG INTEGER NOT NULL,
    TOTAL_KUANTITAS_PENJUALAN_TOKO INTEGER NOT NULL,
    STOK_TOKO INTEGER NOT NULL,
    GOLONGAN VARCHAR(6) NOT NULL
);         
ALTER TABLE PUBLIC.MST_BARANG ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(PLU);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MST_BARANG;              
CREATE CACHED TABLE PUBLIC.MST_GOLONGAN_BARANG(
    ID VARCHAR(6) NOT NULL,
    GOLONGAN_BARANG VARCHAR(50)
);             
ALTER TABLE PUBLIC.MST_GOLONGAN_BARANG ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MST_GOLONGAN_BARANG;     
CREATE CACHED TABLE PUBLIC.MST_HPP_BARANG(
    ID_HPP VARCHAR(8) NOT NULL,
    HPP DECIMAL(19, 2) NOT NULL,
    HPP_SATUAN DECIMAL(19, 2) NOT NULL,
    ISI INTEGER NOT NULL,
    TANGGAL TIMESTAMP,
    BARANG VARCHAR(8) NOT NULL
); 
ALTER TABLE PUBLIC.MST_HPP_BARANG ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID_HPP);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MST_HPP_BARANG;          
CREATE CACHED TABLE PUBLIC.MST_RUNNING_NUMBER(
    ID VARCHAR(255) NOT NULL,
    NUMBER INTEGER
);         
ALTER TABLE PUBLIC.MST_RUNNING_NUMBER ADD CONSTRAINT PUBLIC.CONSTRAINT_B4 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MST_RUNNING_NUMBER;      
CREATE CACHED TABLE PUBLIC.MST_SATUAN_BARANG(
    ID VARCHAR(6) NOT NULL,
    SATUAN_BARANG VARCHAR(50)
); 
ALTER TABLE PUBLIC.MST_SATUAN_BARANG ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MST_SATUAN_BARANG;       
CREATE CACHED TABLE PUBLIC.MST_SUPPLIER(
    ID VARCHAR(6) NOT NULL,
    ALAMAT_SUPPLIER VARCHAR(100),
    EMAIL VARCHAR(50),
    KONTAK_HP VARCHAR(20),
    KODE_POS VARCHAR(10),
    KOTA VARCHAR(20),
    NAMA_SUPPLIER VARCHAR(30),
    SALDO_HUTANG DECIMAL(19, 2),
    KONTAK_TELEPON VARCHAR(20)
);          
ALTER TABLE PUBLIC.MST_SUPPLIER ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MST_SUPPLIER;            
CREATE CACHED TABLE PUBLIC.TR_PELUNASAN_HUTANG(
    NO_REF VARCHAR(15) NOT NULL,
    JLH_BAYAR DECIMAL(19, 2),
    NO_KWITANSI VARCHAR(20),
    PEMBUAT VARCHAR(255),
    TANGGAL TIMESTAMP,
    SUPPLIER VARCHAR(6)
);
ALTER TABLE PUBLIC.TR_PELUNASAN_HUTANG ADD CONSTRAINT PUBLIC.CONSTRAINT_1D PRIMARY KEY(NO_REF);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TR_PELUNASAN_HUTANG;     
CREATE CACHED TABLE PUBLIC.TR_PEMBELIAN(
    NO_REF VARCHAR(15) NOT NULL,
    JUMLAH_BAYAR DECIMAL(19, 2),
    JUMLAH_KREDIT DECIMAL(19, 2),
    SISA_KREDIT DECIMAL(19, 2),
    TANGGAL_TEMPO DATE,
    KREDIT BOOLEAN NOT NULL,
    LOKASI VARCHAR(255),
    NO_FAKTUR VARCHAR(20),
    PEMBUAT VARCHAR(255),
    TANGGAL TIMESTAMP,
    TOTAL DECIMAL(19, 2),
    SUPPLIER VARCHAR(6)
);      
ALTER TABLE PUBLIC.TR_PEMBELIAN ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(NO_REF);       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TR_PEMBELIAN;            
CREATE CACHED TABLE PUBLIC.TR_PEMBELIAN_DETAIL(
    ID VARCHAR(20) NOT NULL,
    HARGA_BELI DECIMAL(19, 2) NOT NULL,
    ISI_PEMBELIAN INTEGER NOT NULL,
    KUANTITAS INTEGER NOT NULL,
    SATUAN_PEMBELIAN VARCHAR(20),
    STOK_GUDANG INTEGER NOT NULL,
    STOK_TOKO INTEGER NOT NULL,
    SUB_TOTAL DECIMAL(19, 2) NOT NULL,
    UPDATE BOOLEAN NOT NULL,
    BARANG VARCHAR(8) NOT NULL,
    PEMBELIAN VARCHAR(15) NOT NULL
);            
ALTER TABLE PUBLIC.TR_PEMBELIAN_DETAIL ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TR_PEMBELIAN_DETAIL;     
CREATE CACHED TABLE PUBLIC.TR_PULUNASAN_HUTANG_DETAIL(
    ID VARCHAR(20) NOT NULL,
    HUTANG_AKHIR DECIMAL(19, 2),
    PEMBAYARAN DECIMAL(19, 2),
    SISA_HUTANG DECIMAL(19, 2),
    PELUNASAN_HUTANG VARCHAR(15) NOT NULL,
    PEMBELIAN VARCHAR(15) NOT NULL
);   
ALTER TABLE PUBLIC.TR_PULUNASAN_HUTANG_DETAIL ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TR_PULUNASAN_HUTANG_DETAIL;              
ALTER TABLE PUBLIC.MST_HPP_BARANG ADD CONSTRAINT PUBLIC.FK_GVA3Q10T22US7VFSN6EDV7236 FOREIGN KEY(BARANG) REFERENCES PUBLIC.MST_BARANG(PLU) NOCHECK;           
ALTER TABLE PUBLIC.TR_PULUNASAN_HUTANG_DETAIL ADD CONSTRAINT PUBLIC.FK_VQAYVPB509A4CPDINJ6M73RA FOREIGN KEY(PELUNASAN_HUTANG) REFERENCES PUBLIC.TR_PELUNASAN_HUTANG(NO_REF) NOCHECK;          
ALTER TABLE PUBLIC.MST_BARANG ADD CONSTRAINT PUBLIC.FK_LJX1PSWMJFHJW0B7OSLSQN5HU FOREIGN KEY(GOLONGAN) REFERENCES PUBLIC.MST_GOLONGAN_BARANG(ID) NOCHECK;     
ALTER TABLE PUBLIC.TR_PEMBELIAN ADD CONSTRAINT PUBLIC.FK_885DIJR153MU3XHD8IBS34HO9 FOREIGN KEY(SUPPLIER) REFERENCES PUBLIC.MST_SUPPLIER(ID) NOCHECK;          
ALTER TABLE PUBLIC.TR_PEMBELIAN_DETAIL ADD CONSTRAINT PUBLIC.FK_O7IBIG320OVA4TWX4MY7T9273 FOREIGN KEY(PEMBELIAN) REFERENCES PUBLIC.TR_PEMBELIAN(NO_REF) NOCHECK;              
ALTER TABLE PUBLIC.TR_PELUNASAN_HUTANG ADD CONSTRAINT PUBLIC.FK_1M1PXCISJ5VHNQAKD7WTL70V2 FOREIGN KEY(SUPPLIER) REFERENCES PUBLIC.MST_SUPPLIER(ID) NOCHECK;   
ALTER TABLE PUBLIC.TR_PULUNASAN_HUTANG_DETAIL ADD CONSTRAINT PUBLIC.FK_5C50JSXPQ7L3L74QGS1CJ4HUU FOREIGN KEY(PEMBELIAN) REFERENCES PUBLIC.TR_PEMBELIAN(NO_REF) NOCHECK;       
ALTER TABLE PUBLIC.TR_PEMBELIAN_DETAIL ADD CONSTRAINT PUBLIC.FK_7XW31M1P96VQVMNTCDRLNNERD FOREIGN KEY(BARANG) REFERENCES PUBLIC.MST_BARANG(PLU) NOCHECK;      
