/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aangirsang.girsang.toko.toolbar;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JToolBar;

/**
 *
 * @author ITSUSAHBRO
 */
public class ToolbarDenganFilter extends javax.swing.JPanel {

    /**
     * Creates new form Button
     */
    public ToolbarDenganFilter() {
        initComponents();
    }

    public JButton getBtnBaru() {
        return btnBaru;
    }

    public JButton getBtnCari() {
        return btnCari;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public JButton getBtnHapus() {
        return btnHapus;
    }
    public JButton getBtnFilter() {
        return btnFilter;
    }

    public JButton getBtnKeluar() {
        return btnKeluar;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }


    public JToolBar getToolBar() {
        return toolBar;
    }

    public JTextField getTxtCari() {
        return txtCari;
    }
    
    public JLabel getlblKet(){
        return lblKet;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        btnBaru = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnFilter = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnKeluar = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        lblKet = new javax.swing.JLabel();

        toolBar.setBorder(null);
        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        btnBaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/app-icon-32.png"))); // NOI18N
        btnBaru.setText("Baru");
        btnBaru.setFocusable(false);
        btnBaru.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBaru.setMaximumSize(new java.awt.Dimension(55, 57));
        btnBaru.setMinimumSize(new java.awt.Dimension(55, 57));
        btnBaru.setPreferredSize(new java.awt.Dimension(55, 57));
        btnBaru.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnBaru);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/app-edit-icon-32.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setMaximumSize(new java.awt.Dimension(55, 57));
        btnEdit.setMinimumSize(new java.awt.Dimension(55, 57));
        btnEdit.setPreferredSize(new java.awt.Dimension(55, 57));
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnEdit);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/app-delete-icon-32.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setFocusable(false);
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.setMaximumSize(new java.awt.Dimension(55, 57));
        btnHapus.setMinimumSize(new java.awt.Dimension(55, 57));
        btnHapus.setPreferredSize(new java.awt.Dimension(55, 57));
        btnHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnHapus);
        toolBar.add(jSeparator1);

        btnFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/find-icon.png"))); // NOI18N
        btnFilter.setText("Filter");
        btnFilter.setFocusable(false);
        btnFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFilter.setMaximumSize(new java.awt.Dimension(55, 57));
        btnFilter.setMinimumSize(new java.awt.Dimension(55, 57));
        btnFilter.setPreferredSize(new java.awt.Dimension(55, 57));
        btnFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnFilter);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/database_refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setMaximumSize(new java.awt.Dimension(55, 57));
        btnRefresh.setMinimumSize(new java.awt.Dimension(55, 57));
        btnRefresh.setPreferredSize(new java.awt.Dimension(55, 57));
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnRefresh);
        toolBar.add(jSeparator2);

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout-icon-32.png"))); // NOI18N
        btnKeluar.setText("Tutup");
        btnKeluar.setFocusable(false);
        btnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKeluar.setMaximumSize(new java.awt.Dimension(55, 57));
        btnKeluar.setMinimumSize(new java.awt.Dimension(55, 57));
        btnKeluar.setPreferredSize(new java.awt.Dimension(55, 57));
        btnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnKeluar);

        txtCari.setText("jTextField1");

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/find-icon16.png"))); // NOI18N

        lblKet.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblKet.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblKet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCari)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(lblKet)))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JLabel lblKet;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
