/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aangirsang.girsang.toko.ui.master.barang;

import com.aangirsang.girsang.toko.model.master.Barang;
import com.aangirsang.girsang.toko.ui.utama.FrameUtama;
import java.awt.Dimension;
import java.util.List;

/**
 *
 * @author ITSUSAHBRO
 */
public class FilterBarang extends javax.swing.JDialog {
    
    private Barang barang;
    private List<Barang> barangs;

    /**
     * Creates new form FilterBarang
     */
    public FilterBarang() {
        super(FrameUtama.getInstance(), true);
        initComponents();
        clear();
        cboStokToko.setSelectedIndex(0);
    }
    public List<Barang> showDialog(){
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);

        return this.barangs;
    }
    private void clear(){
        txtStokTokoMin.setText("");
        txtStockTokoMax.setText("");
        txtStockTokoMax.setEditable(false);
        txtStokTokoMin.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboStokToko = new javax.swing.JComboBox<>();
        txtStokTokoMin = new javax.swing.JTextField();
        lblStokToko = new javax.swing.JLabel();
        txtStockTokoMax = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FilterBarang.class, "FilterBarang.jLabel1.text")); // NOI18N

        cboStokToko.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Tidak Difilter--", "=", "<>", ">", ">=", "<", "<=", "Diantara", "Tidak Diantara", "Mengandung", "Dimulai Dengan", "Diakhiri Dengan" }));
        cboStokToko.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboStokTokoItemStateChanged(evt);
            }
        });

        txtStokTokoMin.setText(org.openide.util.NbBundle.getMessage(FilterBarang.class, "FilterBarang.txtStokTokoMin.text")); // NOI18N

        lblStokToko.setText(org.openide.util.NbBundle.getMessage(FilterBarang.class, "FilterBarang.lblStokToko.text")); // NOI18N

        txtStockTokoMax.setText(org.openide.util.NbBundle.getMessage(FilterBarang.class, "FilterBarang.txtStockTokoMax.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cboStokToko, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStokTokoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStokToko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(txtStockTokoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboStokToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStokTokoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStokToko)
                    .addComponent(txtStockTokoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOk.setText(org.openide.util.NbBundle.getMessage(FilterBarang.class, "FilterBarang.btnOk.text")); // NOI18N

        btnBatal.setText(org.openide.util.NbBundle.getMessage(FilterBarang.class, "FilterBarang.btnBatal.text")); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboStokTokoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboStokTokoItemStateChanged
        if(cboStokToko.getSelectedIndex()!=0){
            txtStockTokoMax.setEditable(true);
            txtStokTokoMin.setEditable(true);
        }else{
            clear();
        }
    }//GEN-LAST:event_cboStokTokoItemStateChanged

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cboStokToko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStokToko;
    private javax.swing.JTextField txtStockTokoMax;
    private javax.swing.JTextField txtStokTokoMin;
    // End of variables declaration//GEN-END:variables
}
